version: "3"

services:
  db: 
    container_name: postgres
    image: postgres:14.1-alpine
    volumes:
      - .:/usr/db/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: delliv  
    restart: unless-stopped
    networks:
      - backend
   
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-code-challenge
    depends_on:
      db:
        condition: service_started
    ports: 
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/delliv?schema=public
    volumes:
      - .:/usr/api-code-challenge
    networks:
      - backend

  frontend: 
    build:
      context: ./frontend
      target: production
      dockerfile: Dockerfile
    
    volumes:
        - .:/usr/frontend-code-challenge
        - /usr/frontend-code-challenge/node_modules
        - /usr/frontend-code-challenge/.next
    ports:
      - "3000:3000"
   
networks:
  backend:
    driver: "bridge"